### ISSUE TITLE
3个依赖安装失败

### ISSUE THREAD

**Issue by cherrymars** [XgzK/IP_cistern#1]
time random json
安装时候报
ERROR: Could not find a version that satisfies the requirement time
ERROR: No matching distribution found for time
更换清华源和豆瓣源都没用，请教下大佬是怎么安装成功的

**Comment by XgzK** [comment]
这个一般都是安装python自带的，你运行下py文件试试

**Comment by cherrymars** [comment]
拉了新的文件，装了pysocks 依赖后好了

**Comment by 710465103** [comment]
我也是安装不了，装了pysocks 依赖也是不行

**Comment by XgzK** [comment]
> 我也是安装不了，装了pysocks 依赖也是不行

可以在服务器手动运行下py文件，会提示你缺少什么依赖，如果其他问题可以粘贴错误信息
