### ISSUE TITLE
服务器ip被墙了，curl https://uu-proxy.com/api/free不能返回代理池还有救吗

### ISSUE THREAD

**Issue by jamesyoung233** [XgzK/IP_cistern#10]
大佬，我的服务器ip被墙了，curl https://uu-proxy.com/api/free不能返回代理池还有救吗

**Comment by XgzK** [comment]
> 大佬，我的服务器ip被墙了，curl [https://uu-proxy.com/api/free不能返回代理池还有救吗](https://uu-proxy.com/api/free%E4%B8%8D%E8%83%BD%E8%BF%94%E5%9B%9E%E4%BB%A3%E7%90%86%E6%B1%A0%E8%BF%98%E6%9C%89%E6%95%91%E5%90%97)

之前运行过还是第一次运行

**Comment by jamesyoung233** [comment]
大佬，再请教一个问题，我的青龙是装在docker里的，ip_broker.py放容器里path填相对路径还是放外边path填绝对路径，我服务器换了IP了，能返回代理池了

**Comment by jamesyoung233** [comment]
![image](https://user-images.githubusercontent.com/14790381/172559152-e23c854c-b715-4576-972c-ec52a0fd291f.png)
大佬，我新设置的，可以获取到ip。但是不显示公网ip，这样正常不正常？

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/14790381/172559152-e23c854c-b715-4576-972c-ec52a0fd291f.png) 大佬，我新设置的，可以获取到ip。但是不显示公网ip，这样正常不正常？

请问青龙什么版本？因为之前青龙不支持代理的，现在知道的2.10版本不支持代理添加，如果是2.12或者更高则支持，如果脚本之前运行过IP被拉黑的化请留言，我会想办法解决，如果第一次就不用了

**Comment by XgzK** [comment]
> 大佬，再请教一个问题，我的青龙是装在docker里的，ip_broker.py放容器里path填相对路径还是放外边path填绝对路径，我服务器换了IP了，能返回代理池了
不放容器里，放服务器上就行了，因为青龙在root/ql目录挂载了青龙配置文件，第一次运行ip_broker.py检测运行是否有问题，而后运行python3 kill.py 
kill.py会自动添加守护进程和释放之前进程，因为如果运行ip_broker.py多次守护进程，会出现一些BUG，

**Comment by jamesyoung233** [comment]
> > 大佬，再请教一个问题，我的青龙是装在docker里的，ip_broker.py放容器里path填相对路径还是放外边path填绝对路径，我服务器换了IP了，能返回代理池了
> > 不放容器里，放服务器上就行了，因为青龙在root/ql目录挂载了青龙配置文件，第一次运行ip_broker.py检测运行是否有问题，而后运行python3 kill.py
> > kill.py会自动添加守护进程和释放之前进程，因为如果运行ip_broker.py多次守护进程，会出现
谢谢大佬，我的青龙是重新安装的，是2.13.2，那个cloudflare Warp是不是还需要安装启用，还是只需要你这个就行了，还有一个问题就是有些获取到的ip检测后发现不通是不是不能用啊，就像这样的
![image](https://user-images.githubusercontent.com/14790381/172628345-20b7c105-303e-45d0-bef1-f721e7a25693.png)

**Comment by XgzK** [comment]
> 
这个和cloudflare Warp没有关系，说明文档中-->查看是否添加成功里面有一个测试代理是否成功的脚本，如果显示你IP就说明没有成功，如果显示代理IP就说明成功了，如果有问题可以反馈我修改脚本

**Comment by jamesyoung233** [comment]
> > > > 大佬，再请教一个问题，我的青龙是装在docker里的，ip_broker.py放容器里path填相对路径还是放外边path填绝对路径，我服务器换了IP了，能返回代理池了
> > > > 不放容器里，放服务器上就行了，因为青龙在root/ql目录挂载了青龙配置文件，第一次运行ip_broker.py检测运行是否有问题，而后运行python3 kill.py
> > > > kill.py会自动添加守护进程和释放之前进程，因为如果运行ip_broker.py多次守护进程，会出现
> > > > 谢谢大佬，我的青龙是重新安装的，是2.13.2，那个cloudflare Warp是不是还需要安装启用，还是只需要你这个就行了，还有一个问题就是有些获取到的ip检测后发现不通是不是不能用啊，就像这样的
> > > > ![image](https://user-images.githubusercontent.com/14790381/172628345-20b7c105-303e-45d0-bef1-f721e7a25693.png)
> 
> 这个和cloudflare Warp没有关系，说明文档中-->查看是否添加成功里面有一个测试代理是否成功的脚本，如果显示你IP就说明没有成功，如果显示代理IP就说明成功了，如果有问题可以反馈我修改脚本

![image](https://user-images.githubusercontent.com/14790381/172744577-04f9f72e-79ba-40ea-ba02-968619d9922f.png)
再次感谢大佬耐心解答，昨天这个测试报错了，刚又试了一下可以了，我现在是把脚本放服务器里，path填了绝对路径，填/root/ql/config/config.sh提示路径不存在，最后说一句，大佬真牛批。

**Comment by XgzK** [comment]
> /root/ql/config/config.sh

/root/ql/config/config.sh是我的青龙的绝对路径，有的不是这个
