### ISSUE TITLE
青龙面板v2.11.3,ip.py运行可返回代理ip，但后续运行返回空值

### ISSUE THREAD

**Issue by AlfredUtopia** [XgzK/IP_cistern#11]
ip.py运行结果：
![image](https://user-images.githubusercontent.com/53133313/173211695-c3562899-48a3-49a7-9de0-31131b269d1d.png)

实际其他脚本运行结果：
![image](https://user-images.githubusercontent.com/53133313/173211724-5f04049f-6a72-4123-96e0-ac5a4d7e6a74.png)

**Comment by XgzK** [comment]
> ip.py运行结果： ![image](https://user-images.githubusercontent.com/53133313/173211695-c3562899-48a3-49a7-9de0-31131b269d1d.png)
> 
> 实际其他脚本运行结果： ![image](https://user-images.githubusercontent.com/53133313/173211724-5f04049f-6a72-4123-96e0-ac5a4d7e6a74.png)

把配置文件里面的网址改成https://ip.tool.lu/就可了，
ip,py如果返回的是代理地址就说明没问题，因为如果代理不可用返回的是错误
之前那个地址好像返回有问题，一切以ip.py返回结果为准

**Comment by XgzK** [comment]
那是代理过期了，稍后会上传大改动版本

AlfredUtopia ***@***.***> 于 2022年6月14日周二 21:50写道：
