### ISSUE TITLE
不懂怎么弄

### ISSUE THREAD

**Issue by Sky-lisc** [XgzK/IP_cistern#14]
新出的代理怎么弄，和视频不一样，不懂弄了，弄重新出个视频教程吗？

**Comment by XgzK** [comment]
> 新出的代理怎么弄，和视频不一样，不懂弄了，弄重新出个视频教程吗？

好的，30分钟内上传新的教程

**Comment by Sky-lisc** [comment]
好的，谢谢，还有一个gz的压缩包是干嘛用的

**Comment by XgzK** [comment]
> 好的，谢谢，还有一个gz的压缩包是干嘛用的

那个就是源代码压缩后的文件，正在准备录制视频，稍后应该就·可以看到了

**Comment by XgzK** [comment]
> 好的，谢谢，还有一个gz的压缩包是干嘛用的

稍等现在代码有问题，正在修改，改好后通知你

**Comment by Sky-lisc** [comment]
> > 好的，谢谢，还有一个gz的压缩包是干嘛用的
> 
> 稍等现在代码有问题，正在修改，改好后通知你

好的

**Comment by Sky-lisc** [comment]
> > 谢谢，还有一个gz的压缩包，用的很好
> 
> 有点等代码现在有问题，正在修改，改好后通知​​你

好了吗？新的视频教程录制好了没？

**Comment by XgzK** [comment]
> > > 谢谢，还有一个gz的压缩包，用的很好
> > 
> > 
> > 有点等代码现在有问题，正在修改，改好后通知​​你
> 
> 好了吗？新的视频教程录制好了没？

[2.1版本](https://youtu.be/i46zEV7Jqig)
换新的代码

**Comment by Sky-lisc** [comment]
> > > > 谢谢，还有一个gz的压缩包，用的很好
> > > 
> > > 
> > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > 
> > 
> > 新的视频教程描述好了没？
> 
> [2.1版本](https://youtu.be/i46zEV7Jqig) 换新的代码

已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'

**Comment by XgzK** [comment]
> 

截图下代码部分，可运行报错

**Comment by Sky-lisc** [comment]
> > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > 
> > > > > 
> > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > 
> > > > 
> > > > 新的视频教程描述好没？
> > > 
> > > 
> > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > 
> > 
> > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> 
> 截图下代码部分，和运行报

**Comment by Sky-lisc** [comment]
> > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > 
> > > > > > 
> > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > 
> > > > > 
> > > > > 新的视频教程描述好没？
> > > > 
> > > > 
> > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > 
> > > 
> > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > 
> > 
> > 截图下代码部分，和运行报

![Screenshot_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)

**Comment by XgzK** [comment]
> > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > 
> > > > > > > 
> > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > 
> > > > > > 
> > > > > > 新的视频教程描述好没？
> > > > > 
> > > > > 
> > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > 
> > > > 
> > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > 
> > > 
> > > 截图下代码部分，和运行报
> 
> ![Screenshot_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)

你看下copy_ip目录下有没有git_poxy.py
如果存在可能需要链接你服务器，如果可以接受操作你服务器的前提下

**Comment by XgzK** [comment]
> > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 新的视频教程描述好没？
> > > > > > > 
> > > > > > > 
> > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > 
> > > > > > 
> > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > 
> > > > > 
> > > > > 截图下代码部分，和运行报
> > > 
> > > 
> > > ![Screenshot_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > 
> > 
> > 你看下copy_ip目录下有没有git_poxy.py 如果存在可能需要链接你服务器，如果可以接受操作你服务器的前提下
> 
> 有这个文件，怎么链接服务器

你如果是服务器可以把IP和密码发我邮箱prestieaetgmts@gmail.com
我在这边操作试下尽量解决，我不能保证解决，所以请考虑清楚，如果代码问题可以改成适合你的

**Comment by Sky-lisc** [comment]
> > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 新的视频教程描述好没？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > 
> > > > > > > 
> > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > 
> > > > > > 
> > > > > > 截图下代码部分，和运行报
> > > > 
> > > > 
> > > > ![Screenshot_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > 
> > > 
> > > 你看下copy_ip目录下有没有git_poxy.py 如果存在可能需要链接你服务器，如果可以接受操作你服务器的前提下
> > 
> > 
> > 有这个文件，怎么链接服务器
> 
> 你如果是服务器可以把IP和密码发我邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com) 我在这边操作试下尽量解决，我不能保证解决，所以请考虑清楚，如果代码问题可以改成适合你的

服务器IP和密码吗？

**Comment by XgzK** [comment]
> > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > 
> > > > > > > 
> > > > > > > 截图下代码部分，和运行报
> > > > > 
> > > > > 
> > > > > ![Screenshot_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > 
> > > > 
> > > > 你看下copy_ip目录下有没有git_poxy.py 如果存在可能需要链接你服务器，如果可以接受操作你服务器的前提下
> > > 
> > > 
> > > 有这个文件，怎么链接服务器
> > 
> > 
> > 你如果是服务器可以把IP和密码发我邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com) 我在这边操作试下尽量解决，我不能保证解决，所以请考虑清楚，如果代码问题可以改成适合你的
> 
> 服务器IP和密码吗？

是的，因为我需要直接连接服务器，如果服务器上有重要数据还请谨慎考虑

**Comment by Sky-lisc** [comment]
> > > > > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 截图下代码部分，和运行报
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![截图_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > 你看下操作拷贝下没有git.py 如果你的服务器可能存在 你的服务器的IP_IP地址可能需要链接
> > > > > > 
> > > > > > 
> > > > > > 有这个文件，怎么链接服务器
> > > > > 
> > > > > 
> > > > > 你是服务器把IP和密码发给我的邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com)
> > > > 
> > > > 
> > > > 服务器IP和密码吗？
> > > 
> > > 
> > > 是的，我需要直接连接服务器，如果服务器因为重要数据还请慎重考虑
> > 
> > 
> > 好
> 
> 请查看留言信箱

已看到，那两个依赖库怎么添加

**Comment by Sky-lisc** [comment]
> > > > > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 截图下代码部分，和运行报
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![截图_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > 你看下操作拷贝下没有git.py 如果你的服务器可能存在 你的服务器的IP_IP地址可能需要链接
> > > > > > 
> > > > > > 
> > > > > > 有这个文件，怎么链接服务器
> > > > > 
> > > > > 
> > > > > 你是服务器把IP和密码发给我的邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com)
> > > > 
> > > > 
> > > > 服务器IP和密码吗？
> > > 
> > > 
> > > 是的，我需要直接连接服务器，如果服务器因为重要数据还请慎重考虑
> > 
> > 
> > 好
> 
> 请查看留言信箱

运行ip.py报错

**Comment by XgzK** [comment]
> > > > > > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 截图下代码部分，和运行报
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![截图_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你看下操作拷贝下没有git.py 如果你的服务器可能存在 你的服务器的IP_IP地址可能需要链接
> > > > > > > 
> > > > > > > 
> > > > > > > 有这个文件，怎么链接服务器
> > > > > > 
> > > > > > 
> > > > > > 你是服务器把IP和密码发给我的邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com)
> > > > > 
> > > > > 
> > > > > 服务器IP和密码吗？
> > > > 
> > > > 
> > > > 是的，我需要直接连接服务器，如果服务器因为重要数据还请慎重考虑
> > > 
> > > 
> > > 好
> > 
> > 
> > 请查看留言信箱
> 
> 运行ip.py报错

python3 kill.py后日志文件有添加成功代理后再试

**Comment by XgzK** [comment]
> > > > > > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 截图下代码部分，和运行报
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![截图_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你看下操作拷贝下没有git.py 如果你的服务器可能存在 你的服务器的IP_IP地址可能需要链接
> > > > > > > 
> > > > > > > 
> > > > > > > 有这个文件，怎么链接服务器
> > > > > > 
> > > > > > 
> > > > > > 你是服务器把IP和密码发给我的邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com)
> > > > > 
> > > > > 
> > > > > 服务器IP和密码吗？
> > > > 
> > > > 
> > > > 是的，我需要直接连接服务器，如果服务器因为重要数据还请慎重考虑
> > > 
> > > 
> > > 好
> > 
> > 
> > 请查看留言信箱
> 
> 运行ip.py报错

![image](https://user-images.githubusercontent.com/97428873/174206493-58b1a757-0a90-498d-b0de-102627038352.png)
添加这个

**Comment by Sky-lisc** [comment]
> > > > > > > > > > > > > > > > > 谢谢，还有一个gz的压缩包，用的很好
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > 有点等代码现在有问题，正在修改，改好后通知​​你
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 新的视频教程描述好没？
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > [2.1版本](https://youtu.be/i46zEV7Jqig)换新的代码
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 已经换了，执行python3 ip_broker.py这个命令还是报错ModuleNotFoundError: No module named 'copy_ip.git_poxy'
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 截图下代码部分，和运行报
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ![截图_2022-06-16-23-36-39-963_com termux](https://user-images.githubusercontent.com/107620570/174108724-8719eefd-d7bb-4119-8565-d9551251bd31.jpg)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你看下操作拷贝下没有git.py 如果你的服务器可能存在 你的服务器的IP_IP地址可能需要链接
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 有这个文件，怎么链接服务器
> > > > > > > 
> > > > > > > 
> > > > > > > 你是服务器把IP和密码发给我的邮箱[prestieaetgmts@gmail.com](mailto:prestieaetgmts@gmail.com)
> > > > > > 
> > > > > > 
> > > > > > 服务器IP和密码吗？
> > > > > 
> > > > > 
> > > > > 是的，我需要直接连接服务器，如果服务器因为重要数据还请慎重考虑
> > > > 
> > > > 
> > > > 好
> > > 
> > > 
> > > 请查看留言信箱
> > 
> > 
> > 运行ip.py报错
> 
> ![图片](https://user-images.githubusercontent.com/97428873/174206493-58b1a757-0a90-498d-b0de-102627038352.png) 添加这个

手机本地青龙现在没有问题了，就是服务器的青龙，运行ip.py还是有报错
![Screenshot_2022-06-17-11-19-30-104_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174221916-e3dea96a-5366-45a1-8cea-c098cbfd195b.jpg)

**Comment by XgzK** [comment]
截图什么错误

Sky-lisc ***@***.***> 于 2022年6月17日周五 11:56写道：
