### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by AlfredUtopia** [XgzK/IP_cistern#15]
root@Tower:/mnt/user/appdata/ql-n# python3 ip_broker.py 
Traceback (most recent call last):
  File "/mnt/user/appdata/ql-n/ip_broker.py", line 3, in <module>
    from copy_ip.git_poxy import get_git_ip
  File "/mnt/user/appdata/ql-n/copy_ip/git_poxy.py", line 6, in <module>
    from copy_ip.other.log import log_ip
  File "/mnt/user/appdata/ql-n/copy_ip/other/log.py", line 6, in <module>
    from copy_ip.conn import read_yaml
  File "/mnt/user/appdata/ql-n/copy_ip/conn.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by XgzK** [comment]
> root@Tower:/mnt/user/appdata/ql-n# python3 ip_broker.py Traceback (most recent call last): File "/mnt/user/appdata/ql-n/ip_broker.py", line 3, in from copy_ip.git_poxy import get_git_ip File "/mnt/user/appdata/ql-n/copy_ip/git_poxy.py", line 6, in from copy_ip.other.log import log_ip File "/mnt/user/appdata/ql-n/copy_ip/other/log.py", line 6, in from copy_ip.conn import read_yaml File "/mnt/user/appdata/ql-n/copy_ip/conn.py", line 4, in import yaml ModuleNotFoundError: No module named 'yaml'

稍等现在代码有问题，正在修改，改好后通知你

**Comment by AlfredUtopia** [comment]
最后用了pip3 install pyyaml命令安装成功yaml..

然后。。。
删库跑路完毕
代理池现在清空[]
什么鬼lol

**Comment by XgzK** [comment]
节点筛选有点慢，第一次运行是空，应该30秒才会出节点，需要运行两次才正常

AlfredUtopia ***@***.***> 于 2022年6月17日周五 23:36写道：

**Comment by AlfredUtopia** [comment]
以下是否还需要用上？
增加代理ip后似乎会影响到有代理后的拉库，提示检查网络
"修改青龙 config.sh 文件中的GithubProxyUrl参数为：
GithubProxyUrl=""

https://gh.fakev.cn/
https://hub.fastgit.xyz/
https://hub.0z.gs/

上面的选取一个在拉取库的时候把github.com替换成自己上面添加的
如设置的是
GithubProxyUrl="https://gh.fakev.cn/"
如库的脚本是 https://github.com/aaa换成https://gh.fakev.cn/aaa"

**Comment by AlfredUtopia** [comment]
> 以下是否还需要用上？ 增加代理ip后似乎会影响到有代理后的拉库，提示检查网络 "修改青龙 config.sh 文件中的GithubProxyUrl参数为： GithubProxyUrl=""
> 
> https://gh.fakev.cn/ https://hub.fastgit.xyz/ https://hub.0z.gs/
> 
> 上面的选取一个在拉取库的时候把github.com替换成自己上面添加的 如设置的是 GithubProxyUrl="https://gh.fakev.cn/" 如库的脚本是 [https://github.com/aaa换成https://gh.fakev.cn/aaa](https://github.com/aaa%E6%8D%A2%E6%88%90https://gh.fakev.cn/aaa)"

已确认GithubProxyUrl="" 不需要添加链接也可运行（实际自己添加了一个内部的代理）

2.11.x确认不适用，2.13.3可用
