### ISSUE TITLE
运行脚本时没有显示IP

### ISSUE THREAD

**Issue by Sky-lisc** [XgzK/IP_cistern#16]
在运行脚本时脚本上怎么没有显示IP，怎么弄才能让脚本显示IP？
![Screenshot_2022-06-17-16-15-04-597_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174256935-4477c1e3-8aad-43b8-90f2-d5db13e40a8a.jpg)

**Comment by XgzK** [comment]
> 在运行脚本时脚本上怎么没有显示IP，怎么弄才能让脚本显示IP？ ![Screenshot_2022-06-17-16-15-04-597_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174256935-4477c1e3-8aad-43b8-90f2-d5db13e40a8a.jpg)

export ALL_PROXY=$ALL_PROXY
echo '当前代理:' $ALL_PROXY
echo '开始查询公网IP:'
curl --silent --location --request GET 'https://ip.tool.lu/'

**Comment by Sky-lisc** [comment]
> > 在运行脚本时，脚本上怎么没有IP，怎么才能让脚本显示IP？![Screenshot_2022-06-17-16-15-04-597_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174256935-4477c1e3-8aad-43b8-90f2-d5db13e40a8a.jpg)
> 
> export ALL_PROXY=$ALL_PROXY echo '当前代理:' $ALL_PROXY echo '开始查询公网IP:' curl --silent --location --request GET ' https://ip.tool.lu/ '

添加显示IP，拉库网络失败
![Screenshot_2022-06-17-19-01-05-757_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174286129-ad630134-debd-438e-86b5-3a4ad466cb88.jpg)

**Comment by XgzK** [comment]
> > > 在运行脚本时，脚本上怎么没有IP，怎么才能让脚本显示IP？![Screenshot_2022-06-17-16-15-04-597_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174256935-4477c1e3-8aad-43b8-90f2-d5db13e40a8a.jpg)
> > 
> > 
> > export ALL_PROXY=$ALL_PROXY echo '当前代理:' $ALL_PROXY echo '开始查询公网IP:' curl --silent --location --request GET ' https://ip.tool.lu/ '
> 
> 添加显示IP，拉库网络失败，删除显示IP就没问题 ![Screenshot_2022-06-17-19-01-05-757_com mmbox xbrowser](https://user-images.githubusercontent.com/107620570/174286129-ad630134-debd-438e-86b5-3a4ad466cb88.jpg)

这个不清楚，个人感觉没必要显示IP，日志文件本身不会查看，添加与否基本没什么必要，如果非要显示可用换个换取IP的网址
