### ISSUE TITLE
IP重复

### ISSUE THREAD

**Issue by Sky-lisc** [XgzK/IP_cistern#18]
这两天获取到的IP都是同样的，
![Screenshot_2022-06-20-17-59-32-494_bin mt plus](https://user-images.githubusercontent.com/107620570/174577676-9e3d30d7-8529-46f8-80a7-29c7e65cc6a8.jpg)

**Comment by XgzK** [comment]
好的，等晚上调试下尽量解决这个问题

Sky-lisc ***@***.***> 于 2022年6月20日周一 18:00写道：

**Comment by XgzK** [comment]
> 这两天获取到的IP都是同样的， ![Screenshot_2022-06-20-17-59-32-494_bin mt plus](https://github.com/assets/107620570/9e3d30d7-8529-46f8-80a7-29c7e65cc6a8)

请问这里选择是国内吗？检测发现国内基本就221.194.181.159:80这个节点可用，而且连续几天都可用，所有如果使用的是国内可能导致大部分都是这个
![image](https://user-images.githubusercontent.com/97428873/174711013-a3b4ba73-6abc-4eb9-948f-e489745aa0d9.png)
