### ISSUE TITLE
这是什么原因？无法进行下一步

### ISSUE THREAD

**Issue by Poison000** [XgzK/IP_cistern#20]
[root@VM-12-7-centos ~]# python3 ip_broker.py
Traceback (most recent call last):
  File "ip_broker.py", line 3, in <module>
    from copy_ip.git_poxy import get_git_ip
  File "/root/copy_ip/git_poxy.py", line 6, in <module>
    from copy_ip.other.log import log_ip
  File "/root/copy_ip/other/log.py", line 8, in <module>
    path = read_yaml()['log']
  File "/root/copy_ip/conn.py", line 18, in read_yaml
    yam = yaml.load(content, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
[root@VM-12-7-centos ~]# python3 kill.py
kill: 参数不够
添加进程守护成功
nohup: 把输出追加到'nohup.out'

**Comment by XgzK** [comment]
> [root@VM-12-7-centos ~]# python3 ip_broker.py Traceback (most recent call last): File "ip_broker.py", line 3, in from copy_ip.git_poxy import get_git_ip File "/root/copy_ip/git_poxy.py", line 6, in from copy_ip.other.log import log_ip File "/root/copy_ip/other/log.py", line 8, in path = read_yaml()['log'] File "/root/copy_ip/conn.py", line 18, in read_yaml yam = yaml.load(content, Loader=yaml.FullLoader) AttributeError: module 'yaml' has no attribute 'FullLoader' [root@VM-12-7-centos ~]# python3 kill.py kill: 参数不够 添加进程守护成功 nohup: 把输出追加到'nohup.out'

python3 ip_broker.py 运行试试提示什么

**Comment by XgzK** [comment]
> > [root@VM-12-7-centos ~]# python3 ip_broker.py Traceback (most recent call last): File "ip_broker.py", line 3, in from copy_ip.git_poxy import get_git_ip File "/root/copy_ip/git_poxy.py", line 6, in from copy_ip.other.log import log_ip File "/root/copy_ip/other/log.py", line 8, in path = read_yaml()['log'] File "/root/copy_ip/conn.py", line 18, in read_yaml yam = yaml.load(content, Loader=yaml.FullLoader) AttributeError: module 'yaml' has no attribute 'FullLoader' [root@VM-12-7-centos ~]# python3 kill.py kill: 参数不够 添加进程守护成功 nohup: 把输出追加到'nohup.out'
> 
> python3 ip_broker.py 运行试试提示什么

pip3 install pyyaml 缺少这个再运行python3 ip_broker.py 如果正常就不缺少东西了
