### ISSUE TITLE
使用ip池后拉库网络错误，是否能排除拉库地址代理？

### ISSUE THREAD

**Issue by AlfredUtopia** [XgzK/IP_cistern#21]
## 开始执行... 2022-06-21 11:13:22

Reset branch 'main'

Your branch is up to date with 'origin/main'.

branch 'main' set up to track 'origin/main'.

开始更新仓库：/ql/data/repo/shufflewzc_faker2_main

Fetching origin

fatal: unable to access 'https://github.com/shufflewzc/faker2.git/': Recv failure: Connection reset by peer

error: could not fetch origin

Reset branch 'main'

Your branch is up to date with 'origin/main'.

branch 'main' set up to track 'origin/main'.

更新/ql/data/repo/shufflewzc_faker2_main失败，请检查网络...

**Comment by XgzK** [comment]
> ## 开始执行... 2022-06-21 11:13:22
> Reset branch 'main'
> 
> Your branch is up to date with 'origin/main'.
> 
> branch 'main' set up to track 'origin/main'.
> 
> 开始更新仓库：/ql/data/repo/shufflewzc_faker2_main
> 
> Fetching origin
> 
> fatal: unable to access 'https://github.com/shufflewzc/faker2.git/': Recv failure: Connection reset by peer
> 
> error: could not fetch origin
> 
> Reset branch 'main'
> 
> Your branch is up to date with 'origin/main'.
> 
> branch 'main' set up to track 'origin/main'.
> 
> 更新/ql/data/repo/shufflewzc_faker2_main失败，请检查网络...

已经更新某个时间段取消代理，请阅读文档设置
