### ISSUE TITLE
大佬，怎么临时禁用这个代理

### ISSUE THREAD

**Issue by jamesyoung233** [XgzK/IP_cistern#23]
大佬，这个程序整理非常好用，偶尔跑某个脚本的时候可能是获取的ip的问题会出错，所以想临时禁用一下代理，有没有方便快捷的操作，禁用后一会儿根据需要再快速启用？

**Comment by XgzK** [comment]
> 大佬，这个程序整理非常好用，偶尔跑某个脚本的时候可能是获取的ip的问题会出错，所以想临时禁用一下代理，有没有方便快捷的操作，禁用后一会儿根据需要再快速启用？

根据需求快速启用这个无法判断，只能在里面添加定时任务，
第一种：等下次获取代理的时候再添加
第二种：设置取消代理后多久再次添加代理

**Comment by XgzK** [comment]
> 大佬，这个程序整理非常好用，偶尔跑某个脚本的时候可能是获取的ip的问题会出错，所以想临时禁用一下代理，有没有方便快捷的操作，禁用后一会儿根据需要再快速启用？

已经添加某个时间段取消代理的定时任务，请阅读说明文档
