### ISSUE TITLE
代理池没有节点了

### ISSUE THREAD

**Issue by cuncun-edg** [XgzK/IP_cistern#27]
![image](https://user-images.githubusercontent.com/77426305/177238889-9eadacb5-fcb2-4601-9686-3c26006f5bab.png)

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/177238889-9eadacb5-fcb2-4601-9686-3c26006f5bab.png)

请问运行的是最新的脚本吗？
可以看下日志显示的有没有异常信息，类似下面的
![image](https://user-images.githubusercontent.com/97428873/177241586-463b1747-ed97-4c0c-80fd-d2fa2376c0d4.png)

我这边运行暂时没有问题
![image](https://user-images.githubusercontent.com/97428873/177241132-6dc3e30d-2011-44cc-a370-d09f232f1571.png)

**Comment by cuncun-edg** [comment]
重新运行，又好了
![image](https://user-images.githubusercontent.com/77426305/177242627-9568679e-0135-4afc-a160-0afa523b5ab6.png)

**Comment by cuncun-edg** [comment]
![image](https://user-images.githubusercontent.com/77426305/177243156-05b1a8e1-53ff-4024-b61c-a3632535b2ab.png)
没有代理的时候还是会添加一个注释符
![image](https://user-images.githubusercontent.com/77426305/177243227-267d06e7-ba46-4152-a89b-e1d214efe32b.png)

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/177243156-05b1a8e1-53ff-4024-b61c-a3632535b2ab.png) 没有代理的时候还是会添加一个注释符 ![image](https://user-images.githubusercontent.com/77426305/177243227-267d06e7-ba46-4152-a89b-e1d214efe32b.png)

用下这个  curl https://uu-proxy.com/api/free   看看返回什么
# 是注释，是所有IP都不可用了添加的

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/177243156-05b1a8e1-53ff-4024-b61c-a3632535b2ab.png) 没有代理的时候还是会添加一个注释符 ![image](https://user-images.githubusercontent.com/77426305/177243227-267d06e7-ba46-4152-a89b-e1d214efe32b.png)

服务器输入这个 curl https://uu-proxy.com/api/free 看看返回什么

\# 是注释，是所有IP都不可用了添加的

**Comment by cuncun-edg** [comment]
![image](https://user-images.githubusercontent.com/77426305/177244352-f8595466-12f8-464b-82d8-fc7042dfab02.png)

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/177244352-f8595466-12f8-464b-82d8-fc7042dfab02.png)

用的是新的脚本吗

**Comment by cuncun-edg** [comment]
是的，我今天才下载的

**Comment by cuncun-edg** [comment]
![image](https://user-images.githubusercontent.com/77426305/177245391-ccb64907-3790-4901-b591-46804c78a1e5.png)
应该是代理池不行吧，你看难得获取到ip，两次还是重复的

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/177245391-ccb64907-3790-4901-b591-46804c78a1e5.png) 应该是代理池不行吧，你看难得获取到ip，两次还是重复的

你选择的应该是国内，国内很少有可以用的，而且很多重复
![image](https://user-images.githubusercontent.com/97428873/177245726-61b12089-3388-4612-8933-c2366a38d4f0.png)

**Comment by cuncun-edg** [comment]
是的

**Comment by XgzK** [comment]
> 是的

国内的节点基本很少有可用的，只是测试节点的时候可以用的多，就一直保留下来了

**Comment by cuncun-edg** [comment]
脚本不支持python2.7吧？

**Comment by XgzK** [comment]
> 脚本不支持python2.7吧？

不清楚，没有用python2的运行过，不过好像个别语法会不支持
