### ISSUE TITLE
作者你好，我在运行成功后出现错误

### ISSUE THREAD

**Issue by wsdjj** [XgzK/IP_cistern#28]
python3 ip_broker.py
python3 kill.py
运行这个两条命令后，配置文件那边有一个ip了
![搜狗截图20220706190407](https://user-images.githubusercontent.com/76938752/177537012-b9d1022d-cb92-4262-a3e4-9f54329ec2b9.png)
然后我运行脚本的时候就出现错误，ip也和配置文件的不一样
![搜狗截图20220706190350](https://user-images.githubusercontent.com/76938752/177537164-512fe889-6316-4d69-9363-4c64d1079934.png)

**Comment by wsdjj** [comment]
不知道是不是ip地址变化造成的

**Comment by XgzK** [comment]
有的IP不显示不是代理问题，后面就没使用这种显示IP的了，说明文档有个显示IP.py脚本可以试下是不是显示代理IP

wsdjj ***@***.***> 于 2022年7月6日周三 19:10写道：

**Comment by XgzK** [comment]
> 不知道是不是ip地址变化造成的

脚本运行的时候会读取配置文件的内容，可能你运行脚本的时候和那你截图的代理不是一个，其实个人不建议显示代理，因为获取IP地址那个网址就读取不出来一些代理IP，给人感觉是不可用的，在添加代理的时候我专门加了一个代理检测，如果检测不通过会无法添加，一个代理成功添加需要经过三个检测，基本可以保证添加的代理支持https下的京东，每个脚本显示IP如果要使用我有时间会找正常多数IP的网址
![image](https://user-images.githubusercontent.com/97428873/177591564-20657b34-92ad-4875-8905-71c97ba2fa3d.png)
![image](https://user-images.githubusercontent.com/97428873/177591779-0e4104b1-45d8-4087-aa9c-e2342c3c9d51.png)
![image](https://user-images.githubusercontent.com/97428873/177591836-bb91ce3b-2d47-4859-8b2e-6a3ba6f7a68c.png)

**Comment by wsdjj** [comment]
谢谢您，现在无论是运行ip.py还是运行脚本的时候，IP都正常显示了
不过还有一个问题，我发现config.sh会明天自己修改，删除我自己写入的cookie
![搜狗截图20220708175444](https://user-images.githubusercontent.com/76938752/177967374-e95965f6-0804-4c98-aa99-ce3b08df7175.png)
一般是在118行后开始删除的，我的conn.yml是这么配置的
![搜狗截图20220708175757](https://user-images.githubusercontent.com/76938752/177967847-bd04a9de-bf09-4884-b4c3-11080873ca05.png)
这个行数是不是要放在配置文件最后一行？

**Comment by XgzK** [comment]
> 这么配置

cookie不用直接添加配置文件
添加图片里面，
删除cookie不清楚因为cookie没有写入里面过，你可以试着把cookie写入图片中的位置
![image](https://user-images.githubusercontent.com/97428873/178034608-57b6f906-d46d-4819-9292-2421dd80ebbc.png)

**Comment by wsdjj** [comment]
我试了两天还是出现配置文件删除的情况，我尝试一下把这个放在最后一行，看看是不是还有这种情况
![搜狗截图20220709165043](https://user-images.githubusercontent.com/76938752/178098972-a7708a55-3d78-4eb1-8205-7a7e2aef1889.png)

**Comment by wsdjj** [comment]
主要是如果放在环境变量那边，那工程量就太大了

**Comment by XgzK** [comment]
> 我试了两天还是出现配置文件删除的情况，我尝试一下把这个放在最后一行，看看是不是还有这种情况 ![搜狗截图20220709165043](https://user-images.githubusercontent.com/76938752/178098972-a7708a55-3d78-4eb1-8205-7a7e2aef1889.png)

这个不清楚我在下面添加了一些内容，而并未有删除文件的情况，可能是你添加的是最后一行，好像不能读取最后一行，你再内容下面加一个或两个空格行，好像最后一行有读取有问题，

**Comment by wsdjj** [comment]
我昨天特地在最后一行添加了一些内容，今天下午最后一行就有删除情况发生，一般要一天时间才看出来，昨天晚上改的，今天下午就会删除配置文件curl --silent --location --request GET 'https://ip.tool.lu/'下面的内容，而上面的内容没有问题
![搜狗截图20220710184242](https://user-images.githubusercontent.com/76938752/178141507-2f2fe318-788d-4559-b177-7210e6e3107f.png)

**Comment by XgzK** [comment]
最后一行读取有点问题，暂时只能最后一行留为空，文档中这里也提了一句，可以把最后一行添加空行，应该下次可能会修复，但是不确定

wsdjj ***@***.***> 于 2022年7月10日周日 18:47写道：

**Comment by wsdjj** [comment]
还是出现修改配置文件的情况😂
我放弃了，我觉得还是专门再建一个新容器跑京东比较好
大佬停止使用这个要怎么弄，就删除那些文件就可以了吗？

**Comment by XgzK** [comment]
> 还是出现修改配置文件的情况😂 我放弃了，我觉得还是专门再建一个新容器跑京东比较好 大佬停止使用这个要怎么弄，就删除那些文件就可以了吗？

ps -ef|grep ip_broker.py |grep -v grep|awk '{print $2}'|xargs kill -9

**Comment by wsdjj** [comment]
![搜狗截图20220718163922](https://user-images.githubusercontent.com/76938752/179474679-d2c44a1a-236b-49b4-899a-6b034fa6ccf8.png)
kill: invalid number 'root'
显示这个，这样子已经成功停止了吗

**Comment by XgzK** [comment]
> ![搜狗截图20220718163922](https://user-images.githubusercontent.com/76938752/179474679-d2c44a1a-236b-49b4-899a-6b034fa6ccf8.png) kill: invalid number 'root' 显示这个，这样子已经成功停止了吗

可以看下日志是否停止打印，如果停止打印就停止了
