### ISSUE TITLE
作者你好，我在成功运行代理后，运行jd脚本仍不可用

### ISSUE THREAD

**Issue by ForYouBlush** [XgzK/IP_cistern#29]
![image](https://user-images.githubusercontent.com/88973476/178089243-cac022b0-1fc8-435d-80db-3b2b8fd19460.png)
期待大佬解答

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/88973476/178089243-cac022b0-1fc8-435d-80db-3b2b8fd19460.png) 期待大佬解答

如果不用代理可以用吗

**Comment by ForYouBlush** [comment]
> > ![image](https://user-images.githubusercontent.com/88973476/178089243-cac022b0-1fc8-435d-80db-3b2b8fd19460.png) 期待大佬解答
> 
> 如果不用代理可以用吗

不能，本身的服务器就是黑了，想着用这个代理运行脚本的，是不是因为代理池的ip也黑了？还是说什么情况呢

**Comment by XgzK** [comment]
> > > ![image](https://user-images.githubusercontent.com/88973476/178089243-cac022b0-1fc8-435d-80db-3b2b8fd19460.png) 期待大佬解答
> > 
> > 
> > 如果不用代理可以用吗
> 
> 不能，本身的服务器就是黑了，想着用这个代理运行脚本的，是不是因为代理池的ip也黑了？还是说什么情况呢

有的是脚本不支持代理，比如禁用重复任务就无法在使用代理的情况下正常运行，不过脚本作者也运行的时候提示不支持代理了，
脚本不能正常运行一般是脚本自身问题，号是黑的，可以手动去活动里面看下是否火爆，如果不支持代理可以设置在脚本运行的时候取消代理
代理只是避免黑IP并不是使用后就立刻不黑，需要一段时间，如果代理选择的CN可能一段时间都是同一个代理
代理脚本只是工具，脚本问题如果不使用代理可以运行，添加代理后异常，才算代理问题，我才有会修复，如果非代理情况下就不可用就需要找脚本作者反馈而不是代理这边，因为这种情况不是代理添加后引起的
