### ISSUE TITLE
代理写入文件更新

### ISSUE THREAD

**Issue by KingBoyAndGirl** [XgzK/IP_cistern#30]
代理写入config.sh文件时，没有更新，日志文件打印
```
              2022-07-14 09:50:17 : 删库跑路完毕
              2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
              2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880

```
而青龙配置文件config.sh文件，没有更新。

**Comment by XgzK** [comment]
> 代理写入config.sh文件时，没有更新，日志文件打印
> 
> ```
>               2022-07-14 09:50:17 : 删库跑路完毕
>               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
>               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> ```
> 
> 而青龙配置文件config.sh文件，没有更新。

你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页

**Comment by KingBoyAndGirl** [comment]
![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892768-a5e2d7e0-12b2-42e9-84ad-e0362945c35f.png)

这是截图，刷新后也不能用

**Comment by KingBoyAndGirl** [comment]
> > 代理写入 config.sh 文件时，没有更新，日志文件打印
> > ```
> >               2022-07-14 09:50:17 : 删库跑路完毕
> >               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
> >               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而青龙配置文件 config.sh 文件，没有更新。
> 
> 你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页



![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892960-4e969fec-4c97-429c-be15-a45bc0739fe2.png)
这是截图，刷新后也没有生效

**Comment by XgzK** [comment]
> > > 代理写入 config.sh 文件时，没有更新，日志文件打印
> > > ```
> > >               2022-07-14 09:50:17 : 删库跑路完毕
> > >               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
> > >               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 而青龙配置文件 config.sh 文件，没有更新。
> > 
> > 
> > 你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页
> 
> ![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892960-4e969fec-4c97-429c-be15-a45bc0739fe2.png) 这是截图，刷新后也没有生效

使用说明文档测试下ip看看返回的什么，直接对比日志的IP就行，如果返回的是IP和面板的不同就拿可能是浏览器缓存问题，如果和面板显示相同再反馈，如果确实存在问题会修复，配置文件添加显示代理那个IP测试的有BUG会导致很多IP无法显示
![image](https://user-images.githubusercontent.com/97428873/178894061-93f64703-e846-40a9-9fbc-78f17db06812.png)

**Comment by KingBoyAndGirl** [comment]
> > > > 代理写入 config.sh 文件时，没有更新，日志文件打印
> > > > ```
> > > >               2022-07-14 09:50:17 : 删库跑路完毕
> > > >               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
> > > >               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 而青龙配置文件 config.sh 文件，没有更新。
> > > 
> > > 
> > > 你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页
> > 
> > 
> > ![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892960-4e969fec-4c97-429c-be15-a45bc0739fe2.png) 这是截图，刷新后也没有生效
> 
> 使用说明文档测试下ip看看返回的什么，直接对比日志的IP就行，如果返回的是IP和面板的不同就拿可能是浏览器缓存问题，如果和面板显示相同再反馈，如果确实存在问题会修复，配置文件添加显示代理那个IP测试的有BUG会导致很多IP无法显示 ![image](https://user-images.githubusercontent.com/97428873/178894061-93f64703-e846-40a9-9fbc-78f17db06812.png)


返回的和浏览器不同，如图所示：
![QQ截图20220714122524](https://user-images.githubusercontent.com/48237066/178898499-d31e3fc9-f854-42fc-83ad-66b82b6d44ed.png)


但在运行脚本时，拿的是浏览器的配置，如图所示：
![QQ截图20220714122720](https://user-images.githubusercontent.com/48237066/178898627-818d8b03-d450-4efd-aa9d-25a37ab85671.png)

**Comment by XgzK** [comment]
> > > > > 代理写入 config.sh 文件时，没有更新，日志文件打印
> > > > > ```
> > > > >               2022-07-14 09:50:17 : 删库跑路完毕
> > > > >               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
> > > > >               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 而青龙配置文件 config.sh 文件，没有更新。
> > > > 
> > > > 
> > > > 你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页
> > > 
> > > 
> > > ![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892960-4e969fec-4c97-429c-be15-a45bc0739fe2.png) 这是截图，刷新后也没有生效
> > 
> > 
> > 使用说明文档测试下ip看看返回的什么，直接对比日志的IP就行，如果返回的是IP和面板的不同就拿可能是浏览器缓存问题，如果和面板显示相同再反馈，如果确实存在问题会修复，配置文件添加显示代理那个IP测试的有BUG会导致很多IP无法显示 ![image](https://user-images.githubusercontent.com/97428873/178894061-93f64703-e846-40a9-9fbc-78f17db06812.png)
> 
> 返回的和浏览器不同，如图所示： ![QQ截图20220714122524](https://user-images.githubusercontent.com/48237066/178898499-d31e3fc9-f854-42fc-83ad-66b82b6d44ed.png)
> 
> 但在运行脚本时，拿的是浏览器的配置，如图所示： ![QQ截图20220714122720](https://user-images.githubusercontent.com/48237066/178898627-818d8b03-d450-4efd-aa9d-25a37ab85671.png)



> > > > > 代理写入 config.sh 文件时，没有更新，日志文件打印
> > > > > ```
> > > > >               2022-07-14 09:50:17 : 删库跑路完毕
> > > > >               2022-07-14 09:50:24 : 本次IP是export ALL_PROXY=socks4://119.23.71.164:8880
> > > > >               2022-07-14 09:50:24 : 写入文件成功,添加代理是: export ALL_PROXY=socks4://119.23.71.164:8880
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 而青龙配置文件 config.sh 文件，没有更新。
> > > > 
> > > > 
> > > > 你添加的是多少行(不能最后一行)，如果运行之前你打开了青龙面板需要刷新网页
> > > 
> > > 
> > > ![QQ截图20220714104113](https://user-images.githubusercontent.com/48237066/178892960-4e969fec-4c97-429c-be15-a45bc0739fe2.png) 这是截图，刷新后也没有生效
> > 
> > 
> > 使用说明文档测试下ip看看返回的什么，直接对比日志的IP就行，如果返回的是IP和面板的不同就拿可能是浏览器缓存问题，如果和面板显示相同再反馈，如果确实存在问题会修复，配置文件添加显示代理那个IP测试的有BUG会导致很多IP无法显示 ![image](https://user-images.githubusercontent.com/97428873/178894061-93f64703-e846-40a9-9fbc-78f17db06812.png)
> 
> 返回的和浏览器不同，如图所示： ![QQ截图20220714122524](https://user-images.githubusercontent.com/48237066/178898499-d31e3fc9-f854-42fc-83ad-66b82b6d44ed.png)
> 
> 但在运行脚本时，拿的是浏览器的配置，如图所示： ![QQ截图20220714122720](https://user-images.githubusercontent.com/48237066/178898627-818d8b03-d450-4efd-aa9d-25a37ab85671.png)

请使用说明文档那个测试IP的，并且表名青龙版本

**Comment by KingBoyAndGirl** [comment]
@XgzK 


青龙版本：[v2.13.3]

蓝色框是使用说明文档测试的，如图：

![QQ截图20220714124215](https://user-images.githubusercontent.com/48237066/178900515-1b27e19f-9d8b-406e-a5d0-b7d77b99b784.png)

**Comment by XgzK** [comment]
> @XgzK
> 
> 青龙版本：[v2.13.3]
> 
> 蓝色框是使用说明文档测试的，如图：
> 
> ![QQ截图20220714124215](https://user-images.githubusercontent.com/48237066/178900515-1b27e19f-9d8b-406e-a5d0-b7d77b99b784.png)
请看文字提示
![image](https://user-images.githubusercontent.com/97428873/178901951-e490d970-6ff0-4afd-b39a-7a5b086b0863.png)

**Comment by XgzK** [comment]
如果还不知道去链接里面跟着操作 https://youtu.be/i46zEV7Jqig?t=423
