### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qq666666qq** [XgzK/IP_cistern#31]
1.代理池可以自己加么比如巨量ip每天赠1000ip（https://www.juliangip.com/）
2.还有能不能在青龙运行脚本，比如task xxx.py
3.大佬能不能帮我改个脚本
![image](https://user-images.githubusercontent.com/109443267/179376388-4ba7e347-f2d5-495d-a56b-940583dd717f.png)
代码抄的你的还有一部分是巨量ip的开发实列（https://www.juliangip.com/help/sdk/http/）

**Comment by qq666666qq** [comment]
![image](https://user-images.githubusercontent.com/109443267/179378005-438abf29-bc30-44e1-a585-b4722fd7ee89.png)
输出是这个样子，但是没有添加到青龙的config.sh

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/109443267/179378005-438abf29-bc30-44e1-a585-b4722fd7ee89.png) 输出是这个样子，但是没有添加到青龙的config.sh

青龙什么版本

**Comment by qq666666qq** [comment]
2.10.3

**Comment by qq666666qq** [comment]
https://www.juliangip.com/help/sdk/http/

**Comment by qq666666qq** [comment]
import requests

# 提取代理API接口，获取1个代理IP
api_url = "https://v1.api.juliangip.com/dynamic/getips?num=1&pt=1&result_type=text&split=1&trade_no=1834987042xxxxxx&sign=9e489baa3bf149593f149d7252efd006"

# 获取API接口返回的代理IP
proxy_ip = requests.get(api_url).text

# 用户名密码认证(动态代理/独享代理)
username = "username"
password = "password"
proxies = {
"http": "http://%(user)s:%(pwd)s@%(proxy)s/" % {"user": username, "pwd": password, "proxy": proxy_ip},
"https": "http://%(user)s:%(pwd)s@%(proxy)s/" % {"user": username, "pwd": password, "proxy": proxy_ip}
}

# 白名单方式（需提前设置白名单）
# proxies = {
#     "http": "http://%(proxy)s/" % {"proxy": proxy_ip},
#     "https": "http://%(proxy)s/" % {"proxy": proxy_ip}
# }

# 要访问的目标网页
target_url = "https://myip.ipip.net/"

# 使用代理IP发送请求
response = requests.get(target_url, proxies=proxies)

# 获取页面内容
if response.status_code == 200:
print(response.text)

**Comment by qq666666qq** [comment]
这个是开发样列

**Comment by qq666666qq** [comment]
import requests

# 提取代理API接口，获取1个代理IP
api_url = "http://v2.api.juliangip.com/dynamic/getips?num=1&pt=1&result_type=text&split=1&trade_no=1476083421105225&sign=1b5d62afb714cbe3ccd"

# 获取API接口返回的代理IP
proxy_ip = requests.get(api_url).text


print(proxy_ip)
#这个是我改的
def get_proxy_ip(proxy_ip):  
            # 写入文件
            try:
                f = open(data['/root/ql5/data/config/config.sh'][i], 'r+', encoding='utf-8')
                flist = f.readlines()
                # ql行数从一开始，python读取从零开始
                try:
                    flist[int(data['131'][i]) - 1] = '{}\n'.format(proxy_ip)
                    log_ip("写入文件成功,添加代理是: " + str(proxy_ip))
                    f = open(data['1'][i], 'w+', encoding='utf-8')
                    f.writelines(flist)
                except Exception as e:
                    log_ip("可能行不存在异常问题，get_proxy_ip：" + str(e))
                    print("可能行不存在异常问题，get_proxy_ip：" + str(e))
                f.close()
            except Exception as e:
                # 打印明显异常信息
                log_ip("可能路径不存在，get_proxy_ip：" + str(e))
                print("可能路径不存在，get_proxy_ip：" + str(e))
  
    #这个加进去就不好使了，不知道为啥，

**Comment by XgzK** [comment]
> 

TG上联系把 @XGZpy
