### ISSUE TITLE
大佬，新版如何过虑国外代理只选择国内代理？

### ISSUE THREAD

**Issue by longgege666** [XgzK/IP_cistern#34]

**Comment by XgzK** [comment]
> _No description provided._

新版本不再支持代理筛选，每次反馈问题都是国内代理

**Comment by longgege666** [comment]
> > _No description provided._
> 
> 新版本不再支持代理筛选，每次反馈问题都是国内代理

哈哈哈哈，我靠，M幸运抽奖这些连接国外代理有点延迟，悲剧了

**Comment by XgzK** [comment]
> > > _No description provided._
> > 
> > 
> > 新版本不再支持代理筛选，每次反馈问题都是国内代理
> 
> 哈哈哈哈，我靠，M幸运抽奖这些连接国外代理有点延迟，悲剧了

垃圾代理本身就延迟高，低的都是付费的

**Comment by longgege666** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 新版本不再支持代理筛选，每次反馈问题都是国内代理
> > 
> > 
> > 哈哈哈哈，我靠，M幸运抽奖这些连接国外代理有点延迟，悲剧了
> 
> 垃圾代理本身就延迟高，低的都是付费的

好的，感谢大佬回复
