### ISSUE TITLE
ip 脚本运行报错

### ISSUE THREAD

**Issue by 202god** [XgzK/IP_cistern#4]
ip脚本运行报这个
## 开始执行... 2022-06-02 13:37:41
当前代理: socks5://106.55.227.232:1024
开始查询公网IP:
当前 IP：106.55.227.232  来自于：中国 广东 广州  电信/联通/移动
Traceback (most recent call last):
  File "ip_broker.py", line 125, in <module>
    while_loop()
  File "ip_broker.py", line 71, in while_loop
    data = get_ip()
  File "ip_broker.py", line 25, in get_ip
    strhtml = requests.get(url).text
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 182, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 47, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

运行其他脚本会出现这个开头
## 开始执行... 2022-06-02 13:35:43

当前代理: socks5://106.55.227.232:1024
开始查询公网IP:
当前 IP：106.55.227.232  来自于：中国 广东 广州  电信/联通/移动

**Comment by XgzK** [comment]
> ip脚本运行报这个
> 
> ## 开始执行...2022-06-02 13:37:41
> 当前代理： socks5：//106.55.227.232：1024 开始查询公网IP： 当前 IP：106.55.227.232 来自于：中国 广东 广州 电信/联通/移动 Traceback （最近的调用最后一次）： 文件 “ip_broker.py”， 第 125 行， in while_loop（） 文件 “ip_broker.py”， 第 71 行， in while_loop data = get_ip（） 文件 “ip_broker.py”， 第 25 行， in get_ip strhtml = requests.get（url）.text File “/usr/lib/python3.8/site-packages/requests/api.py”， 第 76 行， in get return request（'get'， url， params=params， **kwargs） File “/usr/lib/python3.8/site-packages/requests/api.py”， line 61， in request return session.request（method=method， url=url， **kwargs） File “/usr/lib/python3.8/site-packages/requests/sessions.py”， line 530， in request resp = self.send（prep， **send_kwargs） File “/usr/lib/python3.8/site-packages/requests/sessions.py”， 第 643 行， in send r = adapter.send（request， **kwargs） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 412， in send conn = self.get_connection（request.url， proxies） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 309， in get_connection proxy_manager = self.proxy_manager_for（proxy） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 182， in proxy_manager_for manager = self.proxy_manager[proxy] = SOCKSProxyManager（ File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 47， in SOCKSProxyManager raise InvalidSchema（“Missing dependencies for SOCKS support.”） requests.exceptions.InvalidSchema：缺少 SOCKS 支持的依赖项。
> 
> 运行其他脚本会出现这个开头
> 
> ## 开始执行...2022-06-02 13:35:43
> 当前代理： socks5：//106.55.227.232：1024 开始查询公网IP： 当前 IP：106.55.227.232 来自于：中国 广东 广州 电信/联通/移动



> ip脚本运行报这个
> 
> ## 开始执行...2022-06-02 13:37:41
> 当前代理： socks5：//106.55.227.232：1024 开始查询公网IP： 当前 IP：106.55.227.232 来自于：中国 广东 广州 电信/联通/移动 Traceback （最近的调用最后一次）： 文件 “ip_broker.py”， 第 125 行， in while_loop（） 文件 “ip_broker.py”， 第 71 行， in while_loop data = get_ip（） 文件 “ip_broker.py”， 第 25 行， in get_ip strhtml = requests.get（url）.text File “/usr/lib/python3.8/site-packages/requests/api.py”， 第 76 行， in get return request（'get'， url， params=params， **kwargs） File “/usr/lib/python3.8/site-packages/requests/api.py”， line 61， in request return session.request（method=method， url=url， **kwargs） File “/usr/lib/python3.8/site-packages/requests/sessions.py”， line 530， in request resp = self.send（prep， **send_kwargs） File “/usr/lib/python3.8/site-packages/requests/sessions.py”， 第 643 行， in send r = adapter.send（request， **kwargs） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 412， in send conn = self.get_connection（request.url， proxies） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 309， in get_connection proxy_manager = self.proxy_manager_for（proxy） File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 182， in proxy_manager_for manager = self.proxy_manager[proxy] = SOCKSProxyManager（ File “/usr/lib/python3.8/site-packages/requests/adapters.py”， line 47， in SOCKSProxyManager raise InvalidSchema（“Missing dependencies for SOCKS support.”） requests.exceptions.InvalidSchema：缺少 SOCKS 支持的依赖项。
> 
> 运行其他脚本会出现这个开头
> 
> ## 开始执行...2022-06-02 13:35:43
> 当前代理： socks5：//106.55.227.232：1024 开始查询公网IP： 当前 IP：106.55.227.232 来自于：中国 广东 广州 电信/联通/移动

在青龙里面 依赖管理--->python3 中添加 pysocks 依赖

**Comment by 202god** [comment]
谢谢大佬的及时回复，添加依赖后 脚本运行报  我的config 路径也添加了的
## 开始执行... 2022-06-02 15:50:49
当前代理: socks5://106.55.227.232:1024
开始查询公网IP:
当前 IP：106.55.227.232  来自于：中国 广东 广州  电信/联通/移动
节点不可用
节点不可用
节点不可用
Traceback (most recent call last):
  File "ip_broker.py", line 125, in <module>
    while_loop()
  File "ip_broker.py", line 72, in while_loop
    get_random_ip()
  File "ip_broker.py", line 115, in get_random_ip
    f = open(path, 'r+')
FileNotFoundError: [Errno 2] No such file or directory: '/app/QL/config/config.sh'

**Comment by XgzK** [comment]
> aceback (most rec

这是GitHub上这个文件报错还是青龙运行脚本报错

**Comment by XgzK** [comment]
> '/app/QL/config/config.sh

这里报错是你/app/QL/config/config.sh这个目录或者文件不存在

**Comment by 202god** [comment]
> > '/app/QL/config/config.sh
> 
> 这里报错是你/app/QL/config/config.sh这个目录或者文件不存在

我的青龙配置文件就是这个目录啊

**Comment by XgzK** [comment]
> > > '/app/QL/config/config.sh
> > 
> > 
> > 这里报错是你/app/QL/config/config.sh这个目录或者文件不存在
> 
> 我的青龙配置文件就是这个目录啊

要不然你只能用相对目录，把文件放/app/QL/config/ 目录下，用相对目录试试，看看是否报错，

**Comment by beggerlove** [comment]
![Screenshot_2022-06-03-16-23-48-87_fab32b241c9ab51b0e057c943b753947.jpg](https://user-images.githubusercontent.com/65286493/171817486-2c646e1b-22a8-4f2f-81bf-1737a84486c8.jpg)路径正确 运行脚本就报错

**Comment by XgzK** [comment]
> ![Screenshot_2022-06-03-16-23-48-87_fab32b241c9ab51b0e057c943b753947.jpg](https://user-images.githubusercontent.com/65286493/171817486-2c646e1b-22a8-4f2f-81bf-1737a84486c8.jpg)路径正确 运行脚本就报错

请问这是把脚本放到青龙里面了吗

**Comment by beggerlove** [comment]
正确路径  我把root去掉能正常运行了

**Comment by XgzK** [comment]
> 正确路径 我把root去掉能正常运行了

好的稍后会录制个视频出来
