### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 710465103** [XgzK/IP_cistern#5]
ip_broker.py运行结果：
当前代理: socks5://106.55.227.232:1024
开始查询公网IP:
当前 IP：106.55.227.232  来自于：中国 广东 广州  电信/联通/移动
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
爬取失败,请在控制台输入 curl https://uu-proxy.com/api/free 查看是否返回代理池数据，如果返回代理池数据，请在 https://github.com/XgzK/IP_cistern 上提交issue
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
可用代理有： []
Traceback (most recent call last):
  File "/ql/scripts/XgzK_IP_cistern/ip_broker.py", line 153, in <module>
    while_loop()
  File "/ql/scripts/XgzK_IP_cistern/ip_broker.py", line 88, in while_loop
    countdown(data)
  File "/ql/scripts/XgzK_IP_cistern/ip_broker.py", line 62, in countdown
    a2 = data['free']['next_update_date']
TypeError: 'NoneType' object is not subscriptable

控制台输入 curl https://uu-proxy.com/api/free结果
 curl https://uu-proxy.com/api/free
{"success":true,"free":{"created_date":"2022-06-04T08:31:58.784Z","next_update_date":"2022-06-04T08:41:58.784Z","proxies":[{"ip":"182.131.7.141","port":443,"scheme":"http","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:39:14.351Z","last_alive_response_time_ms":293},{"ip":"39.130.150.43","port":80,"scheme":"http","support_https":false,"region":"CN","last_alive_date":"2022-06-04T08:40:32.316Z","last_alive_response_time_ms":166},{"ip":"139.159.243.135","port":80,"scheme":"http","support_https":false,"region":"CN","last_alive_date":"2022-06-04T08:40:11.249Z","last_alive_response_time_ms":103},{"ip":"14.18.112.54","port":22,"scheme":"socks5","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:39:09.123Z","last_alive_response_time_ms":278},{"ip":"43.240.75.45","port":1080,"scheme":"socks5","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:40:08.809Z","last_alive_response_time_ms":1423},{"ip":"139.9.186.25","port":8388,"scheme":"socks5","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:40:39.532Z","last_alive_response_time_ms":511},{"ip":"116.62.229.194","port":3000,"scheme":"socks4","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:40:00.234Z","last_alive_response_time_ms":151},{"ip":"36.137.23.49","port":8888,"scheme":"http","support_https":false,"region":"CN","last_alive_date":"2022-06-04T08:39:50.423Z","last_alive_response_time_ms":169},{"ip":"114.132.74.104","port":8888,"scheme":"socks5","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:39:52.795Z","last_alive_response_time_ms":1628},{"ip":"180.76.102.189","port":1080,"scheme":"socks5","support_https":true,"region":"CN","last_alive_date":"2022-06-04T08:40:41.964Z","last_alive_response_time_ms":92}]}}

**Comment by XgzK** [comment]
> 

请问是在什么环境下，你这种问题我在windows开启VPN的时候遇到过，在开启代理的时候无法使用，而curl正常，

![屏幕截图 2022-06-04 175442](https://user-images.githubusercontent.com/97428873/171994438-0ffb56b4-a5bc-477d-ae0a-c5e42de6dbdc.jpg)

**Comment by 710465103** [comment]
> > 
> 
> 请问是在什么环境下，你这种问题我在windows开启VPN的时候遇到过，在开启代理的时候无法使用，而curl正常，
> 
centos 7.9。不过我后面直接在终端运行就正常，回青龙也看到的代理结果。

**Comment by XgzK** [comment]
脚本就是终端使用的，因为qinglong在服务器挂载的有个目录，直接可以修改，等下会有个视频操作上传，如果有问题可以看一下

**Comment by XgzK** [comment]
> > > 
> > 
> > 
> > 请问是在什么环境下，你这种问题我在windows开启VPN的时候遇到过，在开启代理的时候无法使用，而curl正常，
> 
> centos 7.9。不过我后面直接在终端运行就正常，回青龙也看到的代理结果。

脚本就是终端使用的，因为qinglong在服务器挂载的有个目录，直接可以修改，等下会有个操作视频上传，如果有问题可以看一下。
