### ISSUE TITLE
1，报错配置文件找不到；2，乱改config.sh 加入�，合并分行

### ISSUE THREAD

**Issue by kent9111** [XgzK/IP_cistern#6]
青龙设置定时任务  每半个小时运行一次，会报错找不到config.sh;另脚本修改IP地址时会吧config修改来有些莫名其妙的问题加入：�这个符号。如图：

![image](https://user-images.githubusercontent.com/29189526/172037959-148c0a57-74e8-46f2-b450-1817cfb3bffb.png)
![image](https://user-images.githubusercontent.com/29189526/172037970-edfa1a50-a1ce-4254-b0e6-c72c56cfb378.png)
![image](https://user-images.githubusercontent.com/29189526/172037975-4b035eba-6c7f-42a7-a260-6baf7ad60e0d.png)
![image](https://user-images.githubusercontent.com/29189526/172037982-d2fc2b0c-b7e8-4a22-ad5a-218fc673f51d.png)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
路径 /ql/config/config.sh 不存在，检查路径是否正确，如果路径没有问题，请在 https://github.com/XgzK/IP_cistern 上提交issue
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
可用代理有： ['export ALL_PROXY=socks5://118.25.17.135:2222', 'export ALL_PROXY=http://182.131.7.141:80', 'export ALL_PROXY=socks4://123.56.10.46:8000', 'export ALL_PROXY=socks4://101.71.99.182:3000', 'export ALL_PROXY=socks5://120.77.217.136:10057', 'export ALL_PROXY=socks5://101.200.43.173:8118', 'export ALL_PROXY=socks5://113.128.69.119:1080', 'export ALL_PROXY=socks5://123.116.129.51:1080']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
路径 /ql/config/config.sh 不存在，检查路径是否正确，如果路径没有问题，请在 https://github.com/XgzK/IP_cistern 上提交issue
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
可用代理有： ['export ALL_PROXY=http://182.131.7.141:443', 'export ALL_PROXY=socks5://14.18.112.54:22', 'export ALL_PROXY=socks5://43.240.75.45:1080', 'export ALL_PROXY=socks4://116.62.229.194:3000', 'export ALL_PROXY=socks5://114.132.74.104:8888']

**Comment by XgzK** [comment]
> 龙设置定时任务 每半个小时运行一次，会报错找不到config.s

脚本不是放在青龙里面的，是放在服务器里的，里面有定时任务，开启守护进程就行了，守护进程开启命令在说明文档的最后，文档里面加入了视频教程，可以看视频演示，

**Comment by kent9111** [comment]
我意思是，运行脚本会报 /ql/config/config.sh 不存在的提示错误，本地的config.sh修改export ALL_PROXY=的时候会出现？符号，同时会自动删配置行，比如我有1000行配置行，使用3小时候变成了900行。加入的？符号，会导致配置不符合规则报错。

**Comment by XgzK** [comment]
> 本地的 config.sh 修改export

这个问题之前并没有出现，脚本添加代码只会添加代理或者添 ALL_PROXY=开头的内容，保存的内容必须是可用经过三次检测成功，而后添加
代码提示找不到文件，出现这一行的前提是代码无法在指定路径找不到文件，找不到也可理解成无法打开和读取内容
如果是代码问题你可以测试一下，新建一个文本，代码路径指向新建的文本，在里面添加内容，运行一段时间看下内容是否被修改或者合并现象出现，可能代码因为其他原因出现BUG，但是根据描述内容无法判断是否和代码有关
如果是本脚本问题，本人深感抱歉

**Comment by kent9111** [comment]
问题解决了，原因是如果守护进程执行多次，或者反复执行，会导致config删配配置。。建议优化下脚本。。

**Comment by XgzK** [comment]
> 问题解决了，原因是如果守护进程执行多次，或者反复执行，会导致config删配配置。。建议优化下脚本。。

好的会尽快优化

**Comment by kent9111** [comment]
extra.sh 加入以下代码解决

check_ip_broker_normal(){
    echo "开始检查 ip_broker.py 的在线状态！"
    ps -fe|grep ip_broker.py|grep -v grep
    echo "开始杀死 ip_broker.py 进程！"
    ps -ef|grep ip_broker.py |grep -v grep|awk '{print $1}'|xargs kill -9
    NOWTIME=$(date +%Y-%m-%d-%H-%M-%S)
    i=0
    while ((i<=0)); do
        echo "扫描 ip_broker.py 是否在线"
        ps -fe|grep ip_broker.py|grep -v grep
        if [ $? -ne 0 ]; then
            i=0
            echo $NOWTIME" 扫描结束！ip_broker.py 掉线了不用担心马上重启！"
            cd /ql/scripts/XgzK_IP_cistern
            ps -ef|grep ip_broker|grep -v grep|awk '{print $1}'|xargs kill -9
            cd /ql/scripts/XgzK_IP_cistern
            sed -i 's/\/root\/ql\/config\/config.sh/\/ql\/config\/config.sh/g' /ql/scripts/XgzK_IP_cistern/ip_broker.py
            nohup python3 ip_broker.py &
            ps -fe|grep Daemon |grep -v grep 
            if [ $? -ne 1 ]; then
                i=1
                echo $NOWTIME" ip_broker.py 重启完成！"
                curl "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage?chat_id=$TG_USER_ID&text=ip_broker 已重启完成"
            fi
        else
            i=1
            echo $NOWTIME" 扫描结束！ip_broker 还在！"
        fi
    done
}
