### ISSUE TITLE
ALL_PROXY不生效，还是原来的ip

### ISSUE THREAD

**Issue by liuranya** [XgzK/IP_cistern#7]

**Comment by XgzK** [comment]
> _未提供说明。_

脚本只能保证检测时候代理可用，具体多久可用是不可控制的，代理可用时间正常是三分钟到五分钟，尽量使用新版青龙之前版本有的不支持代理，如果其他情况可详细说明

**Comment by liuranya** [comment]
版本2.10.13
当前代理: http://22x.1x4.1x1.159:80
开始查询公网IP:当前IP: xxxxxxx
设置的all全局代理好像没有生效是不支持么

**Comment by XgzK** [comment]
> 版本2.10.13 当前代理: http://22x.1x4.1x1.159:80 开始查询公网IP:当前IP: xxxxxxx 设置的all全局代理好像没有生效是不支持么

这个版本问题好像是不支持代理，而非脚本问题，之前有人这个版本过，建议升级版本
