### ISSUE TITLE
跑了半天还是没法用

### ISSUE THREAD

**Issue by WGwuzhi** [XgzK/IP_cistern#8]
![image](https://user-images.githubusercontent.com/57304774/172167500-7d9649df-507d-4956-b6a9-6b93b4e6a3c0.png)

**Comment by XgzK** [comment]
> ![image](https://user-images.githubusercontent.com/57304774/172167500-7d9649df-507d-4956-b6a9-6b93b4e6a3c0.png)

不能用不怎么理解，如果添加上无法使用可能因为青龙版本不支持，可以更新新版本试试，如果其他问题请详细描述

**Comment by WGwuzhi** [comment]
1、在服务器直接运行python3 ip_broker.py就是如图输出，只显示了可用代理没有下一步，也没有添加到青龙
2、手动添加一个代理也是用不了
![image](https://user-images.githubusercontent.com/57304774/172184667-8e0defcb-b574-446d-a20f-68f05967c124.png)
![image](https://user-images.githubusercontent.com/57304774/172184620-59c38bf8-3972-4b23-823a-2d720cfbcafe.png)
3、因为现在主流的稳定版本是2.11.3所以我的大部分容器都是这个版本的，问下后续版本能支持2.11.3吗，需要将容器网络类型改为host吗

**Comment by XgzK** [comment]
> 现在主流的稳定版本是2.11.3所以我的大部分容器都是这个版本的，问下后续版本能支持2.11.3吗，

文档最下面有开启守护进程指令，这个你可以看下青龙版本看下多少版本开始支持的，代理一般有效期三分钟，所以才不断更新，支持不支持是青龙版本而非脚本问题
你看下图片里面的代码是否被注释(就是和图片里面相同不)，主要可用代理感觉多的有点不正常，正常一般是一个到四个
![image](https://user-images.githubusercontent.com/97428873/172186302-38f2d948-8711-4601-a893-a477b34f7af0.png)

**Comment by AmazingXiaomi** [comment]
我这边配置了代理，CJ这个脚本也一直黑ip，不知道咋回事，青龙版本2.12.2

**Comment by XgzK** [comment]
> 我这边配置了代理，CJ这个脚本也一直黑ip，不知道咋回事，青龙版本2.12.2，查出来的外网ip也是代理的地址

所有脚本都不可用？
